version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - .mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: birthday-karte
    user: '1000:50'
    command: --innodb-use-native-aio=0
  web: &web_base
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/birthday-karte
    ports:
      - '3000:3000'
    depends_on:
      - db
